language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t knidhan/docker-react -f dockerfile.dev .

script:
    - docker run knidhan/docker-react npm run test  -- --coverage

deploy:
    - provider: elasticbeanstalk
    - region: "us-east-1"
    - app: "DockerReact"
    - env: "DockerReact-env"
    - bucket_name: "elasticbeanstalk-us-east-1-615859161062"
    - bucket_path: "DockerReact"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

