language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t knidhan/docker-react -f dockerfile.dev .

script:
    - docker run -e  CI=true knidhan/docker-react npm run test  -- --coverage

